name: Build and deploy ASP app to Azure Web App - akmaraltaskmanagement

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Restore NuGet packages
        run: nuget restore ktt/ktt.sln

      - name: Build and Publish
        run: msbuild ktt/ktt.sln /nologo /verbosity:m /t:Build /t:Publish /p:Configuration=Release /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:PublishUrl=${{ github.workspace }}/artifacts

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'akmaraltaskmanagement'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D3F701EF2B9F4C7798885B3D952F5F9B }}
          package: '${{ github.workspace }}/artifacts'


