name: Build and deploy ASP app to Azure Web App - akmaraltaskmanagement

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore NuGet packages
        run: nuget restore ktt/ktt.sln  # Adjust YourSolutionFile.sln to your actual solution file

      - name: Publish to folder
        run: msbuild ktt/ktt.sln /nologo /verbosity:m /t:Build /p:_PackageTempDir="\published\" /p:Configuration=Release

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: ASP-app
          path: './artifacts/**'

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: ASP-app
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'akmaraltaskmanagement'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D3F701EF2B9F4C7798885B3D952F5F9B }}
          package: './artifacts'  # Specify the path to your published artifacts
          # Add other deployment parameters as needed
